import Header from '@/components/dashboard/header';
import Sidebar from '@/components/dashboard/sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard - Quik App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='flex border'>
      <Sidebar />
      <section className='flex-grow'>
        <Header />
        {children}
      </section>
    </div>
  );
}
